Add type hints in guided_backprop_deconvnet and test files (#279)
Summary:
Add type hints in guided_backprop_deconvnet and test files
Add type hints in guided_backprop_deconvnet and test files
Pull Request resolved: https://github.com/pytorch/captum/pull/279

Test Plan:
./scripts/run_mypy.sh
No new errors
Existing error
captum/attr/_core/feature_permutation.py:31: error: Argument "forward_func" to "__init__" of "FeatureAblation" has incompatible type "Optional[Callable[..., Any]]"; expected "Callable[..., Any]"

python -m unittest -v tests.attr.test_deconvolution
ok
test_simple_input_conv_deconv (tests.attr.test_deconvolution.Test) ... ok
test_simple_input_conv_neuron_deconv (tests.attr.test_deconvolution.Test) ... ok
test_simple_multi_input_conv_deconv (tests.attr.test_deconvolution.Test) ... /home/subodhlele/github/captum/captum/attr/_utils/gradient.py:32: UserWarning: Input Tensor 1 did not already require gradients, required_grads has been set automatically.
  "required_grads has been set automatically." % index
ok
test_simple_multi_input_conv_neuron_deconv (tests.attr.test_deconvolution.Test) ... ok

----------------------------------------------------------------------
Ran 5 tests in 0.118s

OK

python -m unittest -v tests.attr.test_guided_backprop

Reviewed By: vivekmig

Differential Revision: D19822262

Pulled By: cheetah2216

fbshipit-source-id: 03b08ad0a8fdd332d4c31ebb350724f2225fccc1